use list() to change fs_paths to list
dulwich/dulwich pull request #887
Opened 2021-07-18 04:41 UTC by DedSecer

Using `list()` to format fs_paths will not only access type `str` but also access type `tuple` and type `set`.

2021-07-19 13:46 UTC, jelmer commented
The existing code is meant to e.g. allow a string to be passed in; this PR would change the behaviour in that case.

2021-07-19 13:47 UTC, jelmer requested changes
The existing code is meant to e.g. allow a string to be passed in; this PR would change the behaviour in that case.

2021-07-20 00:32 UTC, DedSecer commented
I think it also work using `list()`(both python2 and python3).
```
>>> list('s')
['s']
```

2021-07-20 00:35 UTC, jelmer commented
It works, but not necessarily in the way you expect:

```
>>> list('foo')
['f', 'o', 'o']
```

2021-07-20 00:55 UTC, DedSecer commented
Sorry.I have pushed a new commit.

2021-07-20 00:59 UTC, jelmer approved these changes

2021-07-20 01:07 UTC, merged

2021-07-20 01:13 UTC, DedSecer commented
by the way.I hope it can be merge into branch 0.19(for python2)

2021-07-20 01:51 UTC, jelmer commented
That branch really only exists for critical bug fixes. Why do you need Python 2?

2021-07-20 02:12 UTC, DedSecer commented
I have some scripts using python2.